export type PostgresTypes =
  | 'BOOLEAN'
  | 'SMALLINT'
  | 'INTEGER'
  | 'BIGINT'
  | 'REAL'
  | 'DOUBLE PRECISION'
  | 'NUMERIC'
  | 'DECIMAL'
  | 'CHARACTER'
  | 'CHARACTER VARYING'
  | 'TEXT'
  | 'DATE'
  | 'TIME'
  | 'TIMESTAMP'
  | 'UUID'
  | 'JSONB'
  | 'ARRAY'
  | 'SERIAL'
  | 'BIGSERIAL';
