import {Client} from 'pg';
import {checkSchemaDrift, generateMigration} from '../../../src/schema';
import {TableDefinition} from '../../../src/types';
import {UsersSchema, usersColumns} from '../../tables/definitions/users';
import {PostsSchema, postsColumns} from '../../tables/definitions/posts';
import {AddressesSchema, addressesColumns} from '../../tables/definitions/addresses';
import {fixtureTablesDdl} from '../live/live-setup';

/**
 * Runs the schema tools over the users, posts and addresses definitions of tests/tables.
 * The examples of docs/features/schema.md come from this file.
 * Skipped unless PGLIGHTQUERY_TEST_DATABASE_URL is set. Each test runs in a transaction that is rolled back.
 */
const databaseUrl = process.env.PGLIGHTQUERY_TEST_DATABASE_URL;
const describeLive = databaseUrl ? describe : describe.skip;

const usersTable: TableDefinition<UsersSchema> = {tableName: 'users', schema: {columns: usersColumns}};
const postsTable: TableDefinition<PostsSchema> = {tableName: 'posts', schema: {columns: postsColumns}};
const addressesTable: TableDefinition<AddressesSchema> = {tableName: 'addresses', schema: {columns: addressesColumns}};
const tables = [usersTable, postsTable, addressesTable];

describeLive('schema tools over the fixture tables', () => {
	let client: Client;
	const query = (text: string, values: any[]) => client.query(text, values);
	const options = {query, defaultSchema: 'fixture_test'};

	beforeEach(async () => {
		client = new Client({connectionString: databaseUrl});
		await client.connect();
		await client.query('BEGIN');
		await client.query('CREATE SCHEMA fixture_test');
	});

	afterEach(async () => {
		await client.query('ROLLBACK');
		await client.end();
	});

	it('drafts the three tables for an empty database, and the draft leaves no drift', async () => {
		const draft = await generateMigration(tables, {...options, format: 'sql'});

		expect(draft.hasChanges).toBe(true);
		expect(draft.needsReview).toBe(false);
		expect(draft.steps.map((step) => step.sql.split('\n')[0])).toEqual([
			'CREATE TABLE "fixture_test"."users" (',
			'CREATE TABLE "fixture_test"."posts" (',
			'CREATE TABLE "fixture_test"."addresses" (',
			'ALTER TABLE "fixture_test"."posts" ADD FOREIGN KEY ("userId") REFERENCES "fixture_test"."users" ("id")',
			'ALTER TABLE "fixture_test"."addresses" ADD FOREIGN KEY ("userId") REFERENCES "fixture_test"."users" ("id")',
		]);
		expect(draft.steps[0].sql).toBe(
			[
				'CREATE TABLE "fixture_test"."users" (',
				'\t"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,',
				'\t"name" text NOT NULL,',
				'\t"email" text UNIQUE,',
				'\t"createdAt" timestamp without time zone NOT NULL DEFAULT NOW(),',
				'\t"updatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),',
				'\t"lastChangedBy" text',
				')',
			].join('\n')
		);

		// The sql format is one file of statements that any migration tool can run.
		await client.query(draft.content);

		const report = await checkSchemaDrift(tables, options);
		expect(report).toEqual({ok: true, issues: []});
	});

	it('finds no drift between the definitions and the DDL the live suites use', async () => {
		await client.query('SET LOCAL search_path TO fixture_test');
		for (const statement of fixtureTablesDdl) {
			await client.query(statement);
		}

		const report = await checkSchemaDrift(tables, options);

		expect(report.issues).toEqual([]);
		expect(report.ok).toBe(true);
	});

	it('reports a definition that moved ahead of the database, and drafts the change', async () => {
		await client.query((await generateMigration(tables, {...options, format: 'sql'})).content);
		await client.query('ALTER TABLE fixture_test.users ADD COLUMN "legacyBio" text');

		// The definition gains a "bio" column. The database still has "legacyBio".
		const usersWithBio: TableDefinition<any> = {
			tableName: 'users',
			schema: {columns: {...usersColumns, bio: {type: 'TEXT'}}},
		};
		const changed = [usersWithBio, postsTable, addressesTable];

		const report = await checkSchemaDrift(changed, options);
		expect(report.ok).toBe(false);
		expect(report.issues.map((issue) => issue.message)).toEqual([
			'fixture_test.users.bio: column does not exist (expected column, found nothing)',
			'fixture_test.users.legacyBio: column is not in the definition (expected nothing, found column)',
		]);

		const draft = await generateMigration(changed, {...options, format: 'node-pg-migrate-ts'});
		expect(draft.hasChanges).toBe(true);
		expect(draft.needsReview).toBe(true);
		expect(draft.content).toBe(
			[
				'// Generated by pg-lightquery generateMigration. Review before running.',
				"import type {MigrationBuilder} from 'node-pg-migrate';",
				'',
				'export async function up(pgm: MigrationBuilder): Promise<void> {',
				'\tpgm.sql(`ALTER TABLE "fixture_test"."users" ADD COLUMN "bio" text`);',
				'',
				'\t// REVIEW: Dropping legacyBio deletes its data. If it was renamed, use: ALTER TABLE "fixture_test"."users" RENAME COLUMN "legacyBio" TO "bio"',
				'\t// pgm.sql(`ALTER TABLE "fixture_test"."users" DROP COLUMN "legacyBio"`);',
				'',
				'\t// No down migration is generated. Add one if you need rollbacks.',
				'}',
				'',
			].join('\n')
		);

		// ignoreExtraColumns leaves the database column alone.
		const additive = await generateMigration(changed, {...options, ignoreExtraColumns: true});
		expect(additive.needsReview).toBe(false);
		expect(additive.steps).toEqual([{sql: 'ALTER TABLE "fixture_test"."users" ADD COLUMN "bio" text', review: false}]);
	});
});
