import {Client} from 'pg';
import {checkSchemaDrift} from '../../../src/schema/schema-drift';
import {generateMigration, renderMigration} from '../../../src/schema/migration-generator';
import {TableDefinition} from '../../../src/types';
import {sqlExpression} from '../../../src/sql/expression';

/**
 * Generates migrations against a real PostgreSQL server, applies them, and checks that no drift remains.
 * Skipped unless PGLIGHTQUERY_TEST_DATABASE_URL is set. Each test runs in a transaction that is rolled back.
 */
const databaseUrl = process.env.PGLIGHTQUERY_TEST_DATABASE_URL;
const describeLive = databaseUrl ? describe : describe.skip;

const table = (tableName: string, columns: Record<string, any>): TableDefinition<any> => ({
	tableName,
	schema: {columns},
});

// Database state that differs from `desiredTables` in every way the generator handles
const EXISTING_SQL = `
CREATE SCHEMA gen_test;
CREATE TYPE gen_test.post_status AS ENUM ('draft', 'published');
CREATE TYPE gen_test.post_visibility AS ENUM ('public', 'private', 'secret');
CREATE TABLE gen_test.users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	name TEXT,
	active BOOLEAN NOT NULL DEFAULT true,
	balance NUMERIC(10, 2),
	meta JSONB,
	"profileVisibility" gen_test.post_visibility
);
CREATE TABLE gen_test.posts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"userId" INTEGER NOT NULL REFERENCES gen_test.users (id) ON DELETE CASCADE,
	"editorId" INTEGER,
	"reviewerId" INTEGER REFERENCES gen_test.users (id),
	status gen_test.post_status NOT NULL DEFAULT 'draft',
	visibility gen_test.post_visibility NOT NULL DEFAULT 'public',
	code TEXT UNIQUE,
	slug TEXT,
	views INTEGER,
	title TEXT,
	summary TEXT NOT NULL
);
CREATE UNIQUE INDEX posts_slug_idx ON gen_test.posts (slug);
CREATE TABLE gen_test.tags (
	id INTEGER PRIMARY KEY,
	label TEXT NOT NULL
);
CREATE TABLE gen_test.codes (
	code TEXT PRIMARY KEY,
	id INTEGER NOT NULL
);
`;

const desiredTables = [
	table('gen_test.users', {
		id: {type: 'INTEGER', primaryKey: true}, // auto increment removed -> review
		email: {type: 'VARCHAR', length: 100, notNull: true, unique: true}, // type change -> review
		name: {type: 'TEXT', notNull: true}, // SET NOT NULL -> review
		active: {type: 'BOOLEAN', notNull: true}, // default removed -> review
		balance: {type: 'NUMERIC', precision: 10, scale: 2, unique: true}, // add unique -> active
		nickname: {type: 'TEXT'}, // add column -> active
		bio: {type: 'TEXT', notNull: true}, // add NOT NULL column -> active with note
		handle: {type: 'TEXT', unique: true}, // add column that a new table references -> active
		// shares post_visibility with posts.visibility -> one recreate step converts both
		profileVisibility: {type: 'ENUM', enum: ['public', 'private'], enumTypeName: 'gen_test.post_visibility'},
		// meta removed -> drop column review, with rename hint
	}),
	table('gen_test.posts', {
		id: {type: 'INTEGER', primaryKey: true, autoIncrement: true},
		userId: {type: 'INTEGER', notNull: true, references: {table: 'gen_test.users', column: 'id', onDelete: 'SET NULL'}}, // replace FK -> review
		editorId: {type: 'INTEGER', references: {table: 'gen_test.users', column: 'id'}}, // add FK -> active
		reviewerId: {type: 'INTEGER'}, // drop FK -> review
		status: {type: 'ENUM', enum: ['draft', 'published', 'archived'], notNull: true, default: 'draft'}, // add value -> active
		visibility: {type: 'ENUM', enum: ['public', 'private'], notNull: true, default: 'public'}, // remove value -> review
		priority: {type: 'ENUM', enum: ['low', 'high'], enumTypeName: 'gen_test.post_priority'}, // new type + column -> active
		code: {type: 'TEXT'}, // drop unique constraint -> review
		slug: {type: 'TEXT'}, // drop unique index -> review
		views: {type: 'BIGINT'}, // type change -> review
		title: {type: 'TEXT', default: 'Untitled'}, // set default -> active
		summary: {type: 'TEXT'}, // DROP NOT NULL -> review
	}),
	table('gen_test.tags', {
		id: {type: 'INTEGER', primaryKey: true, autoIncrement: true}, // add identity -> review
		label: {type: 'TEXT', primaryKey: true}, // primary key change -> review
	}),
	table('gen_test.codes', {
		code: {type: 'TEXT'}, // leaves the primary key and becomes nullable -> review
		id: {type: 'INTEGER', primaryKey: true},
	}),
	table('gen_test.comments', {
		// missing table -> active
		id: {type: 'BIGINT', primaryKey: true, autoIncrement: true},
		postId: {type: 'INTEGER', notNull: true, references: {table: 'gen_test.posts', column: 'id', onDelete: 'CASCADE'}},
		// references a column that this same migration adds to an existing table
		authorHandle: {type: 'TEXT', references: {table: 'gen_test.users', column: 'handle'}},
		body: {type: 'TEXT', notNull: true},
		createdAt: {type: 'TIMESTAMP WITH TIME ZONE', notNull: true, default: 'NOW()'},
	}),
];

describeLive('generateMigration against a live database', () => {
	let client: Client;
	const query = (text: string, values: any[]) => client.query(text, values);

	beforeEach(async () => {
		client = new Client({connectionString: databaseUrl});
		await client.connect();
		await client.query('BEGIN');
	});

	afterEach(async () => {
		await client.query('ROLLBACK');
		await client.end();
	});

	it('creates a schema from nothing, including mutual foreign keys, with no drift left', async () => {
		await client.query('CREATE SCHEMA gen_test');
		const tables = [
			table('gen_test.orgs', {
				id: {type: 'INTEGER', primaryKey: true, autoIncrement: true},
				ownerId: {type: 'INTEGER', references: {table: 'gen_test.people', column: 'id'}},
			}),
			table('gen_test.people', {
				id: {type: 'INTEGER', primaryKey: true, autoIncrement: true},
				orgId: {type: 'INTEGER', notNull: true, references: {table: 'gen_test.orgs', column: 'id'}},
			}),
			table('gen_test.memberships', {
				// composite primary key, and references a table listed after it
				userId: {type: 'INTEGER', primaryKey: true, references: {table: 'gen_test.accounts', column: 'id'}},
				groupId: {type: 'INTEGER', primaryKey: true},
				role: {type: 'ENUM', enum: ['owner', 'member'], notNull: true, default: 'member'},
			}),
			table('gen_test.accounts', {
				id: {type: 'INTEGER', primaryKey: true, autoIncrement: true},
				email: {type: 'VARCHAR', length: 320, notNull: true, unique: true},
				verified: {type: 'BOOLEAN', notNull: true, default: false},
				settings: {type: 'JSONB', notNull: true, default: {theme: "it's `dark` ${x}"}},
				savedQuery: {type: 'JSONB', default: {sql: 'SELECT 1', params: []}}, // plain object: a literal, not an expression
				createdAt: {type: 'TIMESTAMP WITH TIME ZONE', notNull: true, default: sqlExpression('now()')},
			}),
		];

		const draft = await generateMigration(tables, {query});
		expect(draft.hasChanges).toBe(true);
		expect(draft.needsReview).toBe(false);
		for (const step of draft.steps) await client.query(step.sql);

		const report = await checkSchemaDrift(tables, {query});
		expect(report.issues).toEqual([]);

		const {rows} = await client.query(
			`SELECT column_default FROM information_schema.columns WHERE table_schema = 'gen_test' AND table_name = 'accounts' AND column_name = 'savedQuery'`
		);
		expect(rows[0].column_default).toBe(`'{"sql": "SELECT 1", "params": []}'::jsonb`);

		const again = await generateMigration(tables, {query});
		expect(again).toMatchObject({hasChanges: false, needsReview: false, steps: []});
	});

	it('applies only additive steps actively and leaves every removal or change for review', async () => {
		await client.query(EXISTING_SQL);
		const draft = await generateMigration(desiredTables, {query});

		const active = draft.steps.filter((s) => !s.review).map((s) => s.sql);
		expect(active).toEqual([
			`CREATE TYPE "gen_test"."post_priority" AS ENUM ('low', 'high')`,
			[
				'CREATE TABLE "gen_test"."comments" (',
				'\t"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,',
				'\t"postId" integer NOT NULL,',
				'\t"authorHandle" text,',
				'\t"body" text NOT NULL,',
				'\t"createdAt" timestamp with time zone NOT NULL DEFAULT NOW()',
				')',
			].join('\n'),
			'ALTER TABLE "gen_test"."users" ADD UNIQUE ("balance")',
			'ALTER TABLE "gen_test"."users" ADD COLUMN "nickname" text',
			'ALTER TABLE "gen_test"."users" ADD COLUMN "bio" text NOT NULL',
			'ALTER TABLE "gen_test"."users" ADD COLUMN "handle" text UNIQUE',
			`ALTER TYPE "gen_test"."post_status" ADD VALUE IF NOT EXISTS 'archived'`,
			'ALTER TABLE "gen_test"."posts" ADD COLUMN "priority" "gen_test"."post_priority"',
			`ALTER TABLE "gen_test"."posts" ALTER COLUMN "title" SET DEFAULT 'Untitled'`,
			'ALTER TABLE "gen_test"."comments" ADD FOREIGN KEY ("postId") REFERENCES "gen_test"."posts" ("id") ON DELETE CASCADE',
			'ALTER TABLE "gen_test"."comments" ADD FOREIGN KEY ("authorHandle") REFERENCES "gen_test"."users" ("handle")',
			'ALTER TABLE "gen_test"."posts" ADD FOREIGN KEY ("editorId") REFERENCES "gen_test"."users" ("id")',
		]);

		for (const sql of active) await client.query(sql);

		const remaining = await generateMigration(desiredTables, {query});
		expect(remaining.steps.length).toBeGreaterThan(0);
		expect(remaining.steps.every((s) => s.review)).toBe(true);
		// The rename hint for "meta" disappears once "nickname" exists; the review SQL itself is unchanged
		expect(remaining.steps.map((s) => s.sql)).toEqual(draft.steps.filter((s) => s.review).map((s) => s.sql));
	});

	it('produces review SQL that is valid and removes the remaining drift when applied', async () => {
		await client.query(EXISTING_SQL);
		const draft = await generateMigration(desiredTables, {query});
		expect(draft.needsReview).toBe(true);

		for (const step of draft.steps) await client.query(step.sql);

		const report = await checkSchemaDrift(desiredTables, {query});
		expect(report.issues).toEqual([]);
	});

	it('lists every new column as a rename candidate when a column disappears', async () => {
		await client.query(EXISTING_SQL);
		const draft = await generateMigration(desiredTables, {query});
		const drop = draft.steps.find((s) => s.sql.includes('DROP COLUMN "meta"'));
		expect(drop).toMatchObject({review: true});
		expect(drop!.note).toContain(
			'RENAME COLUMN "meta" TO <new name>. New columns in this table: "nickname", "bio", "handle".'
		);
	});

	it('recreates a shared enum type once and converts every column that uses it', async () => {
		await client.query(EXISTING_SQL);
		const draft = await generateMigration(desiredTables, {query});
		const recreate = draft.steps.filter((s) => s.sql.includes('RENAME TO "post_visibility_old"'));
		expect(recreate).toHaveLength(1);
		expect(recreate[0].sql).toContain('ALTER TABLE "gen_test"."users" ALTER COLUMN "profileVisibility" TYPE');
		expect(recreate[0].sql).toContain('ALTER TABLE "gen_test"."posts" ALTER COLUMN "visibility" TYPE');
	});

	it('releases NOT NULL on a column that leaves the primary key', async () => {
		await client.query(EXISTING_SQL);
		const draft = await generateMigration(desiredTables, {query});
		const step = draft.steps.find((s) => s.sql.includes('"gen_test"."codes" DROP CONSTRAINT'));
		expect(step?.sql.split(';\n')).toEqual([
			'ALTER TABLE "gen_test"."codes" DROP CONSTRAINT "codes_pkey"',
			'ALTER TABLE "gen_test"."codes" ALTER COLUMN "code" DROP NOT NULL',
			'ALTER TABLE "gen_test"."codes" ADD PRIMARY KEY ("id")',
		]);
	});

	describe('review steps stay inert', () => {
		const LF = String.fromCharCode(0x0a);
		const CR = String.fromCharCode(0x0d);
		const formats = ['sql', 'node-pg-migrate-ts', 'node-pg-migrate-js'] as const;
		const users = table('gen_test.users', {id: {type: 'INTEGER'}});
		const usersExist = async () => {
			const {rows} = await client.query(`SELECT to_regclass('gen_test.users')::text AS found`);
			return rows[0].found;
		};

		beforeEach(async () => {
			await client.query('CREATE SCHEMA gen_test');
			await client.query('CREATE TABLE gen_test.users (id INTEGER)');
		});

		it('refuses to draft for a database column whose name holds a line break', async () => {
			const payload = `x${LF}DROP TABLE gen_test.users; --`;
			await client.query(`ALTER TABLE gen_test.users ADD COLUMN "${payload}" text`);

			for (const format of formats) {
				await expect(generateMigration([users], {query, format})).rejects.toThrow(
					/^Column name "x\\nDROP TABLE gen_test.users; --" contains a line break/
				);
				await expect(generateMigration([users], {query, format, ignoreExtraColumns: true})).rejects.toThrow(
					/contains a line break/
				);
			}
			expect(await usersExist()).toBe('gen_test.users');
		});

		it('refuses to draft for an enum label or a constraint name that holds a line break', async () => {
			await client.query(`CREATE TYPE gen_test.mood AS ENUM ('ok', 'x${CR}DROP TABLE gen_test.users; --')`);
			await client.query('ALTER TABLE gen_test.users ADD COLUMN mood gen_test.mood');
			const withMood = table('gen_test.users', {
				id: {type: 'INTEGER'},
				mood: {type: 'ENUM', enum: ['ok'], enumTypeName: 'gen_test.mood'},
			});
			for (const format of formats) {
				await expect(generateMigration([withMood], {query, format})).rejects.toThrow(
					/^Enum label .* contains a line break/
				);
			}

			await client.query('ALTER TABLE gen_test.users DROP COLUMN mood');
			await client.query(`ALTER TABLE gen_test.users ADD CONSTRAINT "x${LF}DROP TABLE gen_test.users; --" UNIQUE (id)`);
			for (const format of formats) {
				await expect(generateMigration([users], {query, format})).rejects.toThrow(
					/^(Constraint|Index) name .* contains a line break/
				);
			}
		});

		it('changes nothing when a rendered SQL file with hostile review steps runs', async () => {
			for (const terminator of [LF, CR, CR + LF]) {
				const steps = [
					{
						sql: `ALTER TABLE gen_test.users ALTER COLUMN id SET DEFAULT '1${terminator}'; DROP TABLE gen_test.users; --'`,
						review: true,
						note: `Dropping x${terminator}DROP TABLE gen_test.users; -- deletes its data.`,
					},
				];

				await client.query(renderMigration(steps, 'sql'));

				expect(await usersExist()).toBe('gen_test.users');
			}
		});
	});

	it('adds a missing label to an existing enum type before the column that needs it', async () => {
		await client.query('CREATE SCHEMA gen_test');
		await client.query(`CREATE TYPE gen_test.user_status AS ENUM ('active', 'blocked')`);
		await client.query('CREATE TABLE gen_test.users (id INTEGER PRIMARY KEY)');
		const users = table('gen_test.users', {
			id: {type: 'INTEGER', primaryKey: true},
			status: {type: 'ENUM', enum: ['active', 'blocked', 'archived'], enumTypeName: 'gen_test.user_status'},
		});

		const draft = await generateMigration([users], {query});
		expect(draft.steps).toEqual([
			{sql: `ALTER TYPE "gen_test"."user_status" ADD VALUE IF NOT EXISTS 'archived'`, review: false},
			{sql: 'ALTER TABLE "gen_test"."users" ADD COLUMN "status" "gen_test"."user_status"', review: false},
		]);

		for (const step of draft.steps) await client.query(step.sql);
		expect((await checkSchemaDrift([users], {query})).issues).toEqual([]);
	});

	it('writes string defaults as literals, the compatibility list as expressions, and null as no default', async () => {
		await client.query('CREATE SCHEMA gen_test');
		const people = table('gen_test.people', {
			surname: {type: 'TEXT', default: 'Smith (Jr)'},
			owner: {type: 'TEXT', default: 'current_user'},
			nickname: {type: 'TEXT', default: null},
			createdAt: {type: 'TIMESTAMPTZ', notNull: true, default: 'CURRENT_TIMESTAMP'},
			expiresAt: {type: 'TIMESTAMPTZ', default: sqlExpression("now() + interval '1 day'")},
			opensAt: {type: 'TIME WITHOUT TIME ZONE'},
		});

		const draft = await generateMigration([people], {query});
		expect(draft.needsReview).toBe(false);
		for (const step of draft.steps) await client.query(step.sql);

		const {rows} = await client.query(
			`SELECT column_name, data_type, column_default FROM information_schema.columns
			 WHERE table_schema = 'gen_test' AND table_name = 'people' ORDER BY ordinal_position`
		);
		expect(rows).toEqual([
			{column_name: 'surname', data_type: 'text', column_default: `'Smith (Jr)'::text`},
			{column_name: 'owner', data_type: 'text', column_default: `'current_user'::text`},
			{column_name: 'nickname', data_type: 'text', column_default: null},
			{column_name: 'createdAt', data_type: 'timestamp with time zone', column_default: 'CURRENT_TIMESTAMP'},
			{column_name: 'expiresAt', data_type: 'timestamp with time zone', column_default: `(now() + '1 day'::interval)`},
			{column_name: 'opensAt', data_type: 'time without time zone', column_default: null},
		]);

		// TIMESTAMPTZ, TIME WITHOUT TIME ZONE and default: null all compare clean.
		expect((await checkSchemaDrift([people], {query})).issues).toEqual([]);
		expect(await generateMigration([people], {query})).toMatchObject({hasChanges: false, steps: []});
	});
});
