import * as ts from 'typescript';
import {defaultToSql, generateMigration, renderMigration, MigrationStep} from '../../src/schema/migration-generator';
import {SchemaDriftQueryFn} from '../../src/schema/schema-drift';
import {TableDefinition} from '../../src/types';
import {sqlExpression} from '../../src/utils/sql-expression';

// Empty catalog: every table is missing
const emptyCatalog: SchemaDriftQueryFn = async () => ({rows: []});

const accounts: TableDefinition<any> = {
	tableName: 'accounts',
	schema: {
		columns: {
			id: {type: 'INTEGER', primaryKey: true, autoIncrement: true},
			note: {type: 'TEXT', default: "it's `quoted` ${not a template} \\ backslash"},
		},
	},
};

const steps: MigrationStep[] = [
	{sql: 'CREATE TABLE "public"."a" (\n\t"id" integer\n)', review: false},
	{sql: `ALTER TABLE "public"."a" ALTER COLUMN "id" SET DEFAULT 'x \`y\` \${z} \\ w'`, review: false, note: 'a note'},
	{sql: 'ALTER TABLE "public"."a" DROP COLUMN "old"', review: true, note: 'Dropping old deletes its data.'},
];

/** Runs a generated node-pg-migrate file with a fake MigrationBuilder and returns the SQL it issued */
async function runUp(content: string): Promise<string[]> {
	const js = ts.transpileModule(content, {
		compilerOptions: {module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2018},
	}).outputText;
	const module = {exports: {} as any};
	new Function('module', 'exports', 'require', js)(module, module.exports, require);
	const issued: string[] = [];
	await module.exports.up({sql: (sql: string) => issued.push(sql)});
	return issued;
}

describe('defaultToSql', () => {
	it('renders literals', () => {
		expect(defaultToSql('draft')).toBe("'draft'");
		expect(defaultToSql("it's")).toBe("'it''s'");
		expect(defaultToSql(0)).toBe('0');
		expect(defaultToSql(true)).toBe('TRUE');
		expect(defaultToSql(null)).toBe('NULL');
		expect(defaultToSql({a: 1})).toBe(`'{"a":1}'`);
	});

	it('renders a plain object with a sql key as a JSON literal, not an expression', () => {
		expect(defaultToSql({sql: 'SELECT 1'})).toBe(`'{"sql":"SELECT 1"}'`);
	});

	it('renders expressions', () => {
		expect(defaultToSql(sqlExpression('gen_random_uuid()'))).toBe('gen_random_uuid()');
		expect(defaultToSql('NOW()')).toBe('NOW()');
		expect(defaultToSql('CURRENT_TIMESTAMP')).toBe('CURRENT_TIMESTAMP');
	});

	it('does not treat a string with a statement separator as an expression', () => {
		expect(defaultToSql('now(); DROP TABLE users; select now()')).toBe("'now(); DROP TABLE users; select now()'");
	});
});

describe('renderMigration', () => {
	it('node-pg-migrate TypeScript runs exactly the active steps, escaping template characters', async () => {
		const content = renderMigration(steps, 'node-pg-migrate-ts');
		expect(content).toContain("import type {MigrationBuilder} from 'node-pg-migrate';");
		expect(await runUp(content)).toEqual([steps[0].sql, steps[1].sql]);
	});

	it('node-pg-migrate JavaScript runs exactly the active steps', async () => {
		const content = renderMigration(steps, 'node-pg-migrate-js');
		expect(content).toContain('exports.up = async (pgm) => {');
		expect(await runUp(content)).toEqual([steps[0].sql, steps[1].sql]);
	});

	it('comments out review steps with their note', () => {
		const content = renderMigration(steps, 'node-pg-migrate-ts');
		expect(content).toContain(
			'\t// REVIEW: Dropping old deletes its data.\n\t// pgm.sql(`ALTER TABLE "public"."a" DROP COLUMN "old"`);'
		);
	});

	it('renders plain SQL with review steps commented out', () => {
		const content = renderMigration(steps, 'sql');
		expect(content).toContain('CREATE TABLE "public"."a" (\n\t"id" integer\n);');
		expect(content).toContain('-- a note\nALTER TABLE');
		expect(content).toContain(
			'-- REVIEW: Dropping old deletes its data.\n-- ALTER TABLE "public"."a" DROP COLUMN "old";'
		);
	});
});

describe('generateMigration', () => {
	it('creates missing tables and returns the drift issues it was built from', async () => {
		const draft = await generateMigration([accounts], {query: emptyCatalog, format: 'sql'});
		expect(draft.hasChanges).toBe(true);
		expect(draft.needsReview).toBe(false);
		expect(draft.issues.map((i) => i.kind)).toEqual(['missing_table']);
		expect(draft.steps).toEqual([
			{
				sql:
					'CREATE TABLE "public"."accounts" (\n' +
					'\t"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,\n' +
					"\t\"note\" text DEFAULT 'it''s `quoted` ${not a template} \\ backslash'\n" +
					')',
				review: false,
			},
		]);
		expect(await runUp(renderMigration(draft.steps))).toEqual([draft.steps[0].sql]);
	});

	it('reviews everything that depends on an enum type with no listed values', async () => {
		const posts: TableDefinition<any> = {
			tableName: 'posts',
			schema: {columns: {id: {type: 'INTEGER', primaryKey: true}, status: {type: 'ENUM'}}},
		};
		const comments: TableDefinition<any> = {
			tableName: 'comments',
			schema: {columns: {postId: {type: 'INTEGER', references: {table: 'posts', column: 'id'}}}},
		};
		const draft = await generateMigration([posts, comments], {query: emptyCatalog});
		expect(draft.steps.map((s) => [s.review, s.sql.split('\n')[0]])).toEqual([
			[true, 'CREATE TYPE "public"."posts_status" AS ENUM (/* values */)'],
			[true, 'CREATE TABLE "public"."posts" ('],
			[false, 'CREATE TABLE "public"."comments" ('],
			[true, 'ALTER TABLE "public"."comments" ADD FOREIGN KEY ("postId") REFERENCES "public"."posts" ("id")'],
		]);
	});

	it('gives the exact rename statement when one column disappears and one appears', async () => {
		const table: TableDefinition<any> = {tableName: 'users', schema: {columns: {fullName: {type: 'TEXT'}}}};
		const query: SchemaDriftQueryFn = async (text) => ({
			rows: text.includes('information_schema.columns')
				? [
						{
							table_schema: 'public',
							table_name: 'users',
							column_name: 'name',
							data_type: 'text',
							is_nullable: 'YES',
							column_default: null,
							is_identity: 'NO',
						},
					]
				: [],
		});
		const draft = await generateMigration([table], {query});
		const drop = draft.steps.find((s) => s.sql.includes('DROP COLUMN'));
		expect(drop?.note).toBe(
			'Dropping name deletes its data. If it was renamed, use: ALTER TABLE "public"."users" RENAME COLUMN "name" TO "fullName"'
		);
	});
});
