import {ColumnDefinition, TableDefinition} from '../types';
import {
	compareWithCatalog,
	enumTypeFor,
	enumValues,
	key,
	parseTableName,
	QualifiedName,
	queryFnFrom,
	readCatalog,
	resolveTables,
	ResolvedTable,
	SchemaCatalog,
	SchemaDriftIssue,
	SchemaDriftOptions,
	SQL_DATA_TYPES,
} from './schema-drift';

/**
 * Migration drafts.
 *
 * Turns the differences found by checkSchemaDrift into SQL that brings the database in line with the
 * table definitions. The result is a draft for a human to review and commit, never applied automatically.
 *
 * Safety rule:
 * - Active steps only add things, and fail loudly at migration time if existing data conflicts
 *   (create type/table, add column, add enum value, add unique constraint, add foreign key, set default).
 * - Everything that removes or changes something is emitted commented out with a review note
 *   (drops, DROP/SET NOT NULL, type changes, primary key and identity changes, replacing a foreign key).
 *   A definition that merely forgot a flag can therefore never silently remove a production constraint.
 */

export type MigrationFormat = 'node-pg-migrate-ts' | 'node-pg-migrate-js' | 'sql';

export interface MigrationStep {
	/** SQL for this step. May contain several statements. */
	sql: string;
	/** true when the step is emitted commented out because it removes or changes something */
	review: boolean;
	note?: string;
}

export interface GeneratedMigration {
	/** true when the definitions and the database differ */
	hasChanges: boolean;
	/** true when at least one step is commented out and needs a human decision */
	needsReview: boolean;
	steps: MigrationStep[];
	/** The drift issues the steps were generated from */
	issues: SchemaDriftIssue[];
	/** File content in the requested format, ready to write into the migrations directory */
	content: string;
}

export interface GenerateMigrationOptions extends SchemaDriftOptions {
	/** Output format. Defaults to 'node-pg-migrate-ts'. */
	format?: MigrationFormat;
}

// ---------- SQL rendering ----------

export function quoteIdent(name: string): string {
	return `"${name.replace(/"/g, '""')}"`;
}

function quoteName(name: QualifiedName): string {
	return `${quoteIdent(name.schema)}.${quoteIdent(name.table)}`;
}

function quoteLiteral(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

const FUNCTION_CALL = /^[A-Za-z_][A-Za-z0-9_.]*\s*\([^;]*\)$/;
const SQL_KEYWORD_DEFAULTS = /^(CURRENT_TIMESTAMP|CURRENT_DATE|CURRENT_TIME|LOCALTIMESTAMP|LOCALTIME|CURRENT_USER)$/i;

function isSqlExpression(value: unknown): value is {sql: string} {
	return typeof value === 'object' && value !== null && typeof (value as any).sql === 'string';
}

/** Renders a definition default. {sql} and strings such as 'NOW()' are expressions; everything else is a literal. */
export function defaultToSql(value: unknown): string {
	if (isSqlExpression(value)) return value.sql;
	if (value === null) return 'NULL';
	if (typeof value === 'number' || typeof value === 'bigint') return String(value);
	if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
	if (value instanceof Date) return quoteLiteral(value.toISOString());
	if (typeof value === 'string') {
		const trimmed = value.trim();
		return FUNCTION_CALL.test(trimmed) || SQL_KEYWORD_DEFAULTS.test(trimmed) ? trimmed : quoteLiteral(value);
	}
	return quoteLiteral(JSON.stringify(value));
}

function columnType(table: QualifiedName, column: string, def: ColumnDefinition): string {
	if (def.type === 'ENUM') return quoteName(enumTypeFor(table, column, def));
	if (def.type === 'VARCHAR' && def.length !== undefined) return `varchar(${def.length})`;
	if (def.type === 'NUMERIC' && def.precision !== undefined) return `numeric(${def.precision}, ${def.scale ?? 0})`;
	return SQL_DATA_TYPES[def.type as keyof typeof SQL_DATA_TYPES] ?? String(def.type);
}

function referenceSql(def: ColumnDefinition, defaultSchema: string): string {
	const ref = def.references!;
	return [
		`REFERENCES ${quoteName(parseTableName(ref.table, defaultSchema))} (${quoteIdent(ref.column)})`,
		ref.onDelete && `ON DELETE ${ref.onDelete}`,
		ref.onUpdate && `ON UPDATE ${ref.onUpdate}`,
	]
		.filter(Boolean)
		.join(' ');
}

function columnSql(
	table: QualifiedName,
	column: string,
	def: ColumnDefinition,
	defaultSchema: string,
	inlinePrimaryKey: boolean
): string {
	const parts = [quoteIdent(column), columnType(table, column, def)];
	if (def.autoIncrement) parts.push('GENERATED BY DEFAULT AS IDENTITY');
	if (def.notNull || def.primaryKey) parts.push('NOT NULL');
	if (def.default !== undefined && !def.autoIncrement) parts.push(`DEFAULT ${defaultToSql(def.default)}`);
	if (inlinePrimaryKey) parts.push('PRIMARY KEY');
	else if (def.unique && !def.primaryKey) parts.push('UNIQUE');
	if (def.references) parts.push(referenceSql(def, defaultSchema));
	return parts.join(' ');
}

// ---------- step generation ----------

class StepList {
	readonly types: MigrationStep[] = [];
	readonly tables: MigrationStep[] = [];
	readonly changes: MigrationStep[] = [];
	private plannedTypes = new Set<string>();

	constructor(private catalog: SchemaCatalog) {}

	/** Creates the enum type for a column unless it exists or is already planned */
	ensureEnumType(table: QualifiedName, column: string, def: ColumnDefinition) {
		const type = enumTypeFor(table, column, def);
		const typeKey = key(type.schema, type.table);
		if (this.catalog.enumLabels.has(typeKey) || this.plannedTypes.has(typeKey)) return;
		this.plannedTypes.add(typeKey);
		const values = enumValues(def);
		if (values.length === 0) {
			this.types.push({
				sql: `CREATE TYPE ${quoteName(type)} AS ENUM (/* values */)`,
				review: true,
				note: `Enum type ${type.schema}.${type.table} does not exist and the definition lists no enum values.`,
			});
			return;
		}
		this.types.push({
			sql: `CREATE TYPE ${quoteName(type)} AS ENUM (${values.map(quoteLiteral).join(', ')})`,
			review: false,
		});
	}
}

/** Orders tables so a table is created after the missing tables it references */
function orderByReferences(tables: ResolvedTable[], defaultSchema: string): ResolvedTable[] {
	const byKey = new Map(tables.map((t) => [key(t.name.schema, t.name.table), t]));
	const ordered: ResolvedTable[] = [];
	const visiting = new Set<string>();
	const done = new Set<string>();
	const visit = (table: ResolvedTable) => {
		const tableKey = key(table.name.schema, table.name.table);
		if (done.has(tableKey) || visiting.has(tableKey)) return;
		visiting.add(tableKey);
		for (const def of Object.values(table.columns)) {
			if (!def.references) continue;
			const target = parseTableName(def.references.table, defaultSchema);
			const dependency = byKey.get(key(target.schema, target.table));
			if (dependency && dependency !== table) visit(dependency);
		}
		visiting.delete(tableKey);
		done.add(tableKey);
		ordered.push(table);
	};
	tables.forEach(visit);
	return ordered;
}

function createTableStep(table: ResolvedTable, steps: StepList, defaultSchema: string): MigrationStep {
	const primaryKeys = Object.entries(table.columns)
		.filter(([, def]) => def.primaryKey)
		.map(([column]) => column);
	const lines = Object.entries(table.columns).map(([column, def]) => {
		if (def.type === 'ENUM') steps.ensureEnumType(table.name, column, def);
		return columnSql(table.name, column, def, defaultSchema, primaryKeys.length === 1 && def.primaryKey === true);
	});
	if (primaryKeys.length > 1) lines.push(`PRIMARY KEY (${primaryKeys.map(quoteIdent).join(', ')})`);
	return {sql: `CREATE TABLE ${quoteName(table.name)} (\n\t${lines.join(',\n\t')}\n)`, review: false};
}

function buildSteps(
	targets: ResolvedTable[],
	catalog: SchemaCatalog,
	issues: SchemaDriftIssue[],
	defaultSchema: string
): MigrationStep[] {
	const steps = new StepList(catalog);
	const byLabel = new Map(targets.map((t) => [`${t.name.schema}.${t.name.table}`, t]));
	const primaryKeyHandled = new Set<string>();

	const missingTables = issues.filter((i) => i.kind === 'missing_table').map((i) => byLabel.get(i.table)!);
	for (const table of orderByReferences(missingTables, defaultSchema)) {
		steps.tables.push(createTableStep(table, steps, defaultSchema));
	}

	for (const issue of issues) {
		if (issue.kind === 'missing_table' || !issue.column) continue;
		const table = byLabel.get(issue.table)!;
		const t = quoteName(table.name);
		const c = quoteIdent(issue.column);
		const def = table.columns[issue.column];
		const columnKey = key(table.name.schema, table.name.table, issue.column);
		const dbColumn = catalog.columnsByTable
			.get(key(table.name.schema, table.name.table))
			?.find((col) => col.column_name === issue.column);
		const keys = catalog.keysByColumn.get(columnKey) ?? [];
		const foreignKeys = catalog.foreignKeysByColumn.get(columnKey) ?? [];
		const add = (sql: string, note?: string) => steps.changes.push({sql, review: false, note});
		const review = (sql: string, note: string) => steps.changes.push({sql, review: true, note});
		const dropForeignKeys = () =>
			foreignKeys.map((fk) => `ALTER TABLE ${t} DROP CONSTRAINT ${quoteIdent(fk.constraint_name)}`);
		// Changing a column type fails if its current default cannot be cast, so drop it first and restore the defined one
		const retype = (type: string, using: string) => {
			const hasDefault =
				dbColumn?.column_default != null &&
				dbColumn.is_identity !== 'YES' &&
				!/^nextval\(/i.test(dbColumn.column_default);
			return [
				hasDefault && `ALTER TABLE ${t} ALTER COLUMN ${c} DROP DEFAULT`,
				`ALTER TABLE ${t} ALTER COLUMN ${c} TYPE ${type} USING ${using}`,
				hasDefault &&
					def.default !== undefined &&
					`ALTER TABLE ${t} ALTER COLUMN ${c} SET DEFAULT ${defaultToSql(def.default)}`,
			].filter(Boolean) as string[];
		};

		switch (issue.kind) {
			case 'missing_column': {
				if (def.type === 'ENUM') steps.ensureEnumType(table.name, issue.column, def);
				const sql = `ALTER TABLE ${t} ADD COLUMN ${columnSql(table.name, issue.column, def, defaultSchema, false)}`;
				if (def.primaryKey) {
					review(sql, `${issue.column} is a primary key column. Add it to the primary key by hand.`);
				} else if (def.notNull && def.default === undefined && !def.autoIncrement) {
					add(sql, 'NOT NULL without a default fails if the table has rows. Add a default or backfill first.');
				} else {
					add(sql);
				}
				break;
			}
			case 'extra_column': {
				const missing = issues
					.filter((i) => i.kind === 'missing_column' && i.table === issue.table)
					.map((i) => i.column);
				const rename =
					missing.length > 0
						? ` If it was renamed, use: ALTER TABLE ${t} RENAME COLUMN ${c} TO ${quoteIdent(missing[0]!)}`
						: '';
				review(`ALTER TABLE ${t} DROP COLUMN ${c}`, `Dropping ${issue.column} deletes its data.${rename}`);
				break;
			}
			case 'type_mismatch': {
				if (def.type === 'ENUM') steps.ensureEnumType(table.name, issue.column, def);
				const type = columnType(table.name, issue.column, def);
				const using = def.type === 'ENUM' ? `${c}::text::${type}` : `${c}::${type}`;
				review(
					retype(type, using).join(';\n'),
					`Type change from ${issue.actual} to ${issue.expected}. Check the cast: values may be converted, rounded or rejected.`
				);
				break;
			}
			case 'enum_mismatch': {
				const type = quoteName({schema: dbColumn.udt_schema, table: dbColumn.udt_name});
				const inDb = catalog.enumLabels.get(key(dbColumn.udt_schema, dbColumn.udt_name)) ?? [];
				const defined = enumValues(def);
				for (const value of defined.filter((v) => !inDb.includes(v))) {
					add(`ALTER TYPE ${type} ADD VALUE IF NOT EXISTS ${quoteLiteral(value)}`);
				}
				const removed = inDb.filter((v) => !defined.includes(v));
				if (removed.length > 0) {
					review(
						[
							`ALTER TYPE ${type} RENAME TO ${quoteIdent(`${dbColumn.udt_name}_old`)}`,
							`CREATE TYPE ${type} AS ENUM (${defined.map(quoteLiteral).join(', ')})`,
							...retype(type, `${c}::text::${type}`),
							`DROP TYPE ${quoteName({schema: dbColumn.udt_schema, table: `${dbColumn.udt_name}_old`})}`,
						].join(';\n'),
						`PostgreSQL cannot drop enum values (${removed.join(', ')}). Recreate the type after migrating rows that use them. Other columns using the type must be converted too.`
					);
				}
				break;
			}
			case 'nullability_mismatch': {
				if (def.primaryKey || keys.some((k) => k.is_primary)) break; // handled with the primary key
				if (issue.expected === 'NOT NULL') {
					review(
						`ALTER TABLE ${t} ALTER COLUMN ${c} SET NOT NULL`,
						`Fails if rows contain NULL. Backfill first, e.g. UPDATE ${t} SET ${c} = ... WHERE ${c} IS NULL.`
					);
				} else {
					review(`ALTER TABLE ${t} ALTER COLUMN ${c} DROP NOT NULL`, 'Removes a NOT NULL constraint.');
				}
				break;
			}
			case 'primary_key_mismatch': {
				if (primaryKeyHandled.has(issue.table)) break;
				primaryKeyHandled.add(issue.table);
				const statements: string[] = [];
				const existing = new Set<string>();
				for (const col of catalog.columnsByTable.get(key(table.name.schema, table.name.table)) ?? []) {
					for (const k of catalog.keysByColumn.get(key(table.name.schema, table.name.table, col.column_name)) ?? []) {
						if (k.is_primary && k.constraint_name) existing.add(k.constraint_name);
					}
				}
				existing.forEach((name) => statements.push(`ALTER TABLE ${t} DROP CONSTRAINT ${quoteIdent(name)}`));
				const wanted = Object.entries(table.columns)
					.filter(([, d]) => d.primaryKey)
					.map(([column]) => quoteIdent(column));
				if (wanted.length > 0) statements.push(`ALTER TABLE ${t} ADD PRIMARY KEY (${wanted.join(', ')})`);
				review(
					statements.join(';\n'),
					'Primary key change. Foreign keys that reference the old key must be dropped first and recreated.'
				);
				break;
			}
			case 'unique_mismatch': {
				if (issue.expected === 'unique') {
					add(`ALTER TABLE ${t} ADD UNIQUE (${c})`, 'Fails if the column has duplicate values.');
				} else {
					const drops = keys
						.filter((k) => !k.is_primary)
						.map((k) =>
							k.constraint_name
								? `ALTER TABLE ${t} DROP CONSTRAINT ${quoteIdent(k.constraint_name)}`
								: `DROP INDEX ${quoteName({schema: table.name.schema, table: k.index_name})}`
						);
					review(drops.join(';\n'), 'Removes a unique constraint.');
				}
				break;
			}
			case 'auto_increment_mismatch': {
				if (issue.expected === 'auto increment') {
					review(
						[
							`ALTER TABLE ${t} ALTER COLUMN ${c} DROP DEFAULT`,
							`ALTER TABLE ${t} ALTER COLUMN ${c} ADD GENERATED BY DEFAULT AS IDENTITY`,
							`SELECT setval(pg_get_serial_sequence('${t.replace(/'/g, "''")}', '${issue.column.replace(/'/g, "''")}'), COALESCE(MAX(${c}), 0) + 1, false) FROM ${t}`,
						].join(';\n'),
						'Makes the column an identity column and starts it after the current maximum value.'
					);
				} else {
					const sql =
						dbColumn.is_identity === 'YES'
							? `ALTER TABLE ${t} ALTER COLUMN ${c} DROP IDENTITY`
							: `ALTER TABLE ${t} ALTER COLUMN ${c} DROP DEFAULT`;
					review(sql, 'Removes auto increment. Inserts that omit this column will fail.');
				}
				break;
			}
			case 'default_mismatch': {
				if (def.default !== undefined) {
					add(`ALTER TABLE ${t} ALTER COLUMN ${c} SET DEFAULT ${defaultToSql(def.default)}`);
				} else {
					review(
						`ALTER TABLE ${t} ALTER COLUMN ${c} DROP DEFAULT`,
						'Removes a default. Inserts that omit this column may fail.'
					);
				}
				break;
			}
			case 'reference_mismatch': {
				if (!def.references) {
					review(dropForeignKeys().join(';\n'), 'Removes a foreign key.');
				} else if (foreignKeys.length === 0) {
					add(
						`ALTER TABLE ${t} ADD FOREIGN KEY (${c}) ${referenceSql(def, defaultSchema)}`,
						'Fails if rows reference missing parents.'
					);
				} else {
					review(
						[...dropForeignKeys(), `ALTER TABLE ${t} ADD FOREIGN KEY (${c}) ${referenceSql(def, defaultSchema)}`].join(
							';\n'
						),
						`Replaces the foreign key ${issue.actual} with ${issue.expected}.`
					);
				}
				break;
			}
		}
	}

	return [...steps.types, ...steps.tables, ...steps.changes];
}

// ---------- file rendering ----------

function commentLines(text: string, indent: string): string {
	return text
		.split('\n')
		.map((line) => `${indent}// ${line}`)
		.join('\n');
}

function renderSql(steps: MigrationStep[]): string {
	const body = steps.map((step) => {
		const sql = `${step.sql};`;
		if (step.review) {
			const commented = sql
				.split('\n')
				.map((line) => `-- ${line}`)
				.join('\n');
			return `-- REVIEW: ${step.note}\n${commented}`;
		}
		return step.note ? `-- ${step.note}\n${sql}` : sql;
	});
	return `-- Generated by pg-lightquery generateMigration. Review before applying.\n\n${body.join('\n\n')}\n`;
}

function renderNodePgMigrate(steps: MigrationStep[], language: 'ts' | 'js'): string {
	const indent = '\t';
	const body = steps.map((step) => {
		const literal = step.sql.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
		const call = `pgm.sql(\`${literal}\`);`; // no re-indenting: the file runs exactly the reviewed SQL
		if (step.review) return `${indent}// REVIEW: ${step.note}\n${commentLines(call, indent)}`;
		return step.note ? `${indent}// ${step.note}\n${indent}${call}` : `${indent}${call}`;
	});
	const header = '// Generated by pg-lightquery generateMigration. Review before running.\n';
	const footer = `${indent}// No down migration is generated. Add one if you need rollbacks.`;
	if (language === 'ts') {
		return `${header}import type {MigrationBuilder} from 'node-pg-migrate';\n\nexport async function up(pgm: MigrationBuilder): Promise<void> {\n${body.join('\n\n')}\n\n${footer}\n}\n`;
	}
	return `${header}\n/** @param {import('node-pg-migrate').MigrationBuilder} pgm */\nexports.up = async (pgm) => {\n${body.join('\n\n')}\n\n${footer}\n};\n`;
}

export function renderMigration(steps: MigrationStep[], format: MigrationFormat = 'node-pg-migrate-ts'): string {
	if (format === 'sql') return renderSql(steps);
	return renderNodePgMigrate(steps, format === 'node-pg-migrate-js' ? 'js' : 'ts');
}

/**
 * Generates a draft migration that makes the database match the table definitions.
 * Reads the system catalog only. The draft is meant to be reviewed and committed, not run blindly.
 */
export async function generateMigration(
	tables: TableDefinition<any>[],
	options: GenerateMigrationOptions = {}
): Promise<GeneratedMigration> {
	const defaultSchema = options.defaultSchema ?? 'public';
	const targets = resolveTables(tables, defaultSchema);
	const catalog = await readCatalog(targets, queryFnFrom(options));
	const issues = compareWithCatalog(targets, catalog, defaultSchema, options.ignoreExtraColumns ?? false);
	const steps = buildSteps(targets, catalog, issues, defaultSchema);
	return {
		hasChanges: issues.length > 0,
		needsReview: steps.some((step) => step.review),
		steps,
		issues,
		content: renderMigration(steps, options.format),
	};
}
